SCREEN = [1024, 768]
WORLD = [1024, 768]
TICK = 60

SPEED = (5, 5)
NUMOBSTACLES = 3
OBSTACLERADIUS = 200
OBSTACLESIGMA = 50
OBSTACLEMIN = 25
OBSTACLEPOINTS = 7
OBSTACLEGRIDSIZE = 50
NUMRESOURCES = 20
SEED = 2
HITPOINTS = 25
BASEHITPOINTS = 75
TOWERHITPOINTS = 50



HEROHITPOINTS = 50
BUILDRATE = 180
TOWERFIRERATE = 15
BASEFIRERATE = 20
BULLETRANGE = 150
SMALLBULLETRANGE = 150
BIGBULLETRANGE = 250
TOWERBULLETRANGE = 250
TOWERBULLETDAMAGE = 10
TOWERBULLETSPEED = (20, 20)
TOWERBULLET = "sprites/bullet2.gif"
BASEBULLETRANGE = 200
BASEBULLETDAMAGE = 10
BASEBULLETSPEED = (20, 20)
BASEBULLET = "sprites/bullet2.gif"
SPAWNNUM = 3
MAXSPAWN = 4
AREAEFFECTDAMAGE = 25
AREAEFFECTRATE = 60
AREAEFFECTRANGE = 2
MAXLIVES = 3


SMALLBULLETSPEED = (20, 20)
SMALLBULLETDAMAGE = 1
BIGBULLETSPEED = (20, 20)
BIGBULLETDAMAGE = 5
FIRERATE = 10
DODGERATE = 10




AGENT = "sprites/spartan2.gif"
SMALLBULLET = "sprites/bullet.gif"
BIGBULLET = "sprites/bullet2.gif"
RESOURCE = "sprites/crystal.gif"
GATE = "sprites/mine.gif"
NPC = "sprites/spartan.gif"
JACKAL = "sprites/jackal.gif"
ELITE = "sprites/elite.gif"
CRATE = "sprites/crate.gif"
BASE = "sprites/base.gif"
CRYSTAL = "sprites/crystal.gif"
TREE = "sprites/tree.gif"
MINE = "sprites/mine.gif"
TOWER = "sprites/tower.gif"

INFINITY = float("inf")

